### ISSUE TITLE
when I run E1_GrayScaledTopology.java getting following error please help me

### ISSUE THREAD

**Issue by sureshk543** [sensorstorm/StormCV#4]
nl.tno.stormcv.example.E1_GrayScaledTopology
Exception in thread "main" java.lang.NoClassDefFoundError: nl/tno/stormcv/fetcher/IFetcher
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2442)
	at java.lang.Class.getMethod0(Class.java:2685)
	at java.lang.Class.getMethod(Class.java:1620)
	at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:492)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:484)
Caused by: java.lang.ClassNotFoundException: nl.tno.stormcv.fetcher.IFetcher
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	... 6 more

**Comment by corneversloot** [comment]
It looks like the stormcv jar file is not present in your classpath. In order to run the examples you must add the stormcv-examples/lib directory to your classpath as described on [this wiki page](https://github.com/sensorstorm/StormCV/wiki/Getting_started). I hope this helps!
