### ISSUE TITLE
When I run example in "Deploying" getting following error, please help me

### ISSUE THREAD

**Issue by Qilewuqiong** [sensorstorm/StormCV#6]
Content in worker-6702.log
java.lang.RuntimeException: could not open: rtsp://streaming3.webcam.nl:1935/n302/n302.stream
	at com.xuggle.mediatool.MediaReader.open(MediaReader.java:637) ~[stormjar.jar:na]
	at com.xuggle.mediatool.MediaReader.readPacket(MediaReader.java:434) ~[stormjar.jar:na]
	at nl.tno.stormcv.util.StreamReader.run(StreamReader.java:130) ~[stormjar.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
2016-02-26 16:48:34 n.t.s.u.StreamReader [INFO] Start reading stream: rtsp://streaming3.webcam.nl:1935/n302/n302.stream
2016-02-26 16:48:46 o.ffmpeg [ERROR] [rtsp @ 0x7f8b080091e0] method DESCRIBE failed: 404 Not Found
2016-02-26 16:48:46 n.t.s.u.StreamReader [WARN] Stream closed unexpectatly: could not open: rtsp://streaming3.webcam.nl:1935/n302/n302.stream

**Comment by corneversloot** [comment]
It has been over a year since we made the examples and it seems not all streams mentioned work anymore or have different URL's. It turns out the url for this stream has changed to rtsp://streaming5.webcam.nl:1935/live/N302.stream. So just use that one in the example and it should work.

**Comment by Qilewuqiong** [comment]
Thank you for your help. But recently when I submit topology, I get following error:
content in  supervisor.log:
2016-03-01T07:44:29.325+0800 b.s.d.supervisor [INFO] edde10f7-c420-4f96-a770-de39d68cfbb9 still hasn't started
2016-03-01T07:44:29.828+0800 b.s.d.supervisor [INFO] edde10f7-c420-4f96-a770-de39d68cfbb9 still hasn't started
........

and error information in worker-6702.log:

2016-03-01T07:44:31.224+0800 o.a.s.z.ClientCnxn [INFO] Opening socket connection to server 10.1.1.183/10.1.1.183:2181. Will not attempt to authenticate using SASL (unknown error)

2016-03-01T07:44:32.431+0800 b.s.m.n.Client [ERROR] connection attempt 1 to Netty-Client-server1/10.4.9.196:6700 failed: java.net.ConnectException: connection refused:server1/10.4.9.196:6700

storm version : 0.9.6

**Comment by Qilewuqiong** [comment]
Other information in worker-6700.log
2016-03-02T08:09:54.932+0800 b.s.m.n.Client [ERROR] connection attempt 2 to Netty-Client-server1/10.4.9.196:6703 failed: java.lang.RuntimeException: Returned channel was actually not established

2016-03-02T08:10:07.614+0800 n.t.s.u.c.ConnectorHolder [WARN] Unable to instantiate FileConnector: nl.tno.stormcv.util.connector.S3Connector due to: S3 Key or Secret are not set!

**Comment by corneversloot** [comment]
It looks like you are not able to submit the topology to the cluster since the connection is being refused. Are you sure that you can connect to the Storm cluster using port 6700 (no firewall in the way or other networking issues?).

**Comment by Qilewuqiong** [comment]
Thank you for your reply. The problem go away when I refresh the webpage again and again till the video appear.

**Comment by contrast007** [comment]
I am having two errors while I run E2(FaceDetection example)-
1. java.io.FileNotFoundException: Unable to locate /C:/Users/ayush.a/Downloads/opencv/build/java/x64/opencv_java2411.dll

2. org.apache.storm.zookeeper.server.ServerCnxn$EndOfStreamException: Unable to read additional data from client sessionid 0x154f1f0efa7000e, likely client has closed socket

I have run E1, and it was working fine. Will be grateful for your help.

**Comment by corneversloot** [comment]
I think the second error is a result from the first one.

The first one has to do with loading the OpenCV library which is needed in example 2 (it was not needed in example 1 which is why that executed correctly). Did you specify the correct library for your operating system as described on [the wiki](https://github.com/sensorstorm/StormCV/wiki/Examples)?
If you checked out the master branch you have to use the 2.4.8 version of the opencv library for your OS and not the 2.4.11 one as the example is trying to load now.

**Comment by contrast007** [comment]
Thank you. !st error is resolved. I had to use win64_opencv248.dll(in resources folder) whereas I was using opencv2411.dll.
But I am still stuck with 2nd error. The client is connected before, but terminates early. 
here is the log-
---------------------------------------------------------------------------------------------------------------------------
INFO  org.apache.storm.zookeeper.ClientCnxn - Session establishment complete on server INT-86.sisodomain.com/0:0:0:0:0:0:0:1:2001, sessionid = 0x1550678fa63000c, negotiated timeout = 20000
10820 [Thread-6-EventThread] INFO  org.apache.storm.curator.framework.state.ConnectionStateManager - State change: **CONNECTED**
10820 [Thread-6-EventThread] INFO  backtype.storm.zookeeper - Zookeeper state update: :connected:none
10822 [ProcessThread(sid:0 cport:-1):] INFO  org.apache.storm.zookeeper.server.PrepRequestProcessor - **Processed session termination** for sessionid: 0x1550678fa63000c
10957 [Thread-6] INFO  org.apache.storm.zookeeper.ZooKeeper - Session: 0x1550678fa63000c closed
10957 [Thread-6-EventThread] INFO  org.apache.storm.zookeeper.ClientCnxn - EventThread shut down
10958 [Thread-6] INFO  backtype.storm.utils.StormBoundedExponentialBackoffRetry - The baseSleepTimeMs [1000] the maxSleepTimeMs [30000] the maxRetries [5]
10959 [Thread-6] INFO  org.apache.storm.curator.framework.imps.CuratorFrameworkImpl - Starting
10960 [Thread-6] INFO  org.apache.storm.zookeeper.ZooKeeper - Initiating client connection, connectString=localhost:2001/storm sessionTimeout=20000 watcher=org.apache.storm.curator.ConnectionState@229514df
10970 [Thread-6-SendThread(INT-86.sisodomain.com:2001)] INFO  org.apache.storm.zookeeper.ClientCnxn - Opening socket connection to server INT-86.sisodomain.com/0:0:0:0:0:0:0:1:2001. Will not attempt to authenticate using SASL (unknown error)
10972 [Thread-6-SendThread(INT-86.sisodomain.com:2001)] INFO  org.apache.storm.zookeeper.ClientCnxn - Socket connection established to INT-86.sisodomain.com/0:0:0:0:0:0:0:1:2001, initiating session
10975 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2001] WARN  org.apache.storm.zookeeper.server.NIOServerCnxn - caught end of stream exception
org.apache.storm.zookeeper.server.ServerCnxn$EndOfStreamException: Unable to read additional data from client sessionid 0x1550678fa63000c, likely client has closed socket

**Comment by corneversloot** [comment]
It does not really throw an error so im not sure if something really goes wrong. Example 2 does not really show anything, it just writes the results (detected faces) to the specified output directory. There are only a few images to process so this goes very fast. Did you check the output directory (default = /output/facedetections/) to see if it contains results?

**Comment by contrast007** [comment]
That is the problem, It shows no errors but there is no output to the directory. 
**input files** - files.add( "**C:/Users/ayush.a/Downloads/StormCV-master/StormCV-master/stormcv-examples/resources/data/faces5.jpg**" );
		files.add( "C:/Users/ayush.a/Downloads/StormCV-master/StormCV-master/stormcv-examples/resources/data/faces8.jpg" );

**output directory -** 
builder.setBolt("drawer", new SingleInputBolt(new DrawFeaturesOp().destination("**C:/Users/ayush.a/Downloads/StormCV-master/StormCV-master/stormcv-examples/output/facedetections/**")), 1)
					.shuffleGrouping("face_extraction");

**Comment by Yitian-Zhang** [comment]
Have you solved this problem? @contrast007
